# Generated by Django 6.0.2 on 2026-03-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
